using Autodesk.Revit.UI;

namespace RevitCommandLine.Models;
public class CommandIdentificator
{
    private readonly Dictionary<string, RevitCommandId> commandIds = [];
    public CommandIdentificator()
    {
        InitializeStandardCommands(ref commandIds);
    }

    public RevitCommandId GetPostableCommandByCommandId(string commandId) => commandIds[commandId];

    //unfortunatelly there is no other way to get the PostableCommand from the commandId
    //we have to assign commandId to the internal PostableCommand enum manually
    //this is a workaround for the Revit API limitation
    private void InitializeStandardCommands(ref Dictionary<string, RevitCommandId> commandIds)
    {
        //Arhitecture
        commandIds.Add("ID_BUTTON_SELECT", RevitCommandId.LookupPostableCommandId(PostableCommand.SelectionBox));
        commandIds.Add("ID_OBJECTS_WALL", RevitCommandId.LookupPostableCommandId(PostableCommand.ArchitecturalWall));
        commandIds.Add("ID_OBJECTS_STRUCTURAL_WALL", RevitCommandId.LookupPostableCommandId(PostableCommand.StructuralWall));
        commandIds.Add("ID_INPLACE_WALL", RevitCommandId.LookupPostableCommandId(PostableCommand.Wall));
        commandIds.Add("ID_WALL_PICK_FACES", RevitCommandId.LookupPostableCommandId(PostableCommand.WallByFaceWall));
        commandIds.Add("ID_OBJECTS_CORNICE", RevitCommandId.LookupPostableCommandId(PostableCommand.SweepWall));
        commandIds.Add("ID_OBJECTS_REVEAL", RevitCommandId.LookupPostableCommandId(PostableCommand.RevealWall));
        commandIds.Add("ID_OBJECTS_DOOR", RevitCommandId.LookupPostableCommandId(PostableCommand.Door));
        commandIds.Add("ID_OBJECTS_WINDOW", RevitCommandId.LookupPostableCommandId(PostableCommand.Window));
        commandIds.Add("ID_OBJECTS_FAMSYM", RevitCommandId.LookupPostableCommandId(PostableCommand.PlaceAComponent));
        commandIds.Add("ID_INPLACE_COMPONENT", RevitCommandId.LookupPostableCommandId(PostableCommand.ModelInPlace));
        commandIds.Add("ID_OBJECTS_STRUCTURAL_COLUMN", RevitCommandId.LookupPostableCommandId(PostableCommand.StructuralColumn));
        commandIds.Add("ID_OBJECTS_COLUMN", RevitCommandId.LookupPostableCommandId(PostableCommand.ArchitecturalColumn));
        commandIds.Add("ID_ROOF_FOOTPRINT", RevitCommandId.LookupPostableCommandId(PostableCommand.RoofByFootprint));
        commandIds.Add("ID_ROOF_EXTRUSION", RevitCommandId.LookupPostableCommandId(PostableCommand.RoofByExtrusion));
        commandIds.Add("ID_ROOF_PICK_FACES", RevitCommandId.LookupPostableCommandId(PostableCommand.RoofByFace));
        commandIds.Add("ID_CREATE_SOFFIT_TB", RevitCommandId.LookupPostableCommandId(PostableCommand.Soffit));
        commandIds.Add("ID_CREATE_FASCIA_TB", RevitCommandId.LookupPostableCommandId(PostableCommand.Fascia));
        commandIds.Add("ID_CREATE_GUTTER_TB", RevitCommandId.LookupPostableCommandId(PostableCommand.Gutter));
        commandIds.Add("ID_OBJECTS_CEILING", RevitCommandId.LookupPostableCommandId(PostableCommand.AutomaticCeiling));
        commandIds.Add("ID_OBJECTS_FLOOR", RevitCommandId.LookupPostableCommandId(PostableCommand.ArchitecturalFloor));
        commandIds.Add("ID_OBJECTS_SLAB", RevitCommandId.LookupPostableCommandId(PostableCommand.StructuralFloor));
        commandIds.Add("ID_FLOOR_PICK_FACES", RevitCommandId.LookupPostableCommandId(PostableCommand.FloorByFaceFloor));
        commandIds.Add("ID_CREATE_SLAB_EDGE_TB", RevitCommandId.LookupPostableCommandId(PostableCommand.SlabEdgeFloor));
        commandIds.Add("ID_CURTA_SYSTEM_PICK_FACES", RevitCommandId.LookupPostableCommandId(PostableCommand.CurtainSystemByFace));
        commandIds.Add("ID_OBJECTS_CW_GRID", RevitCommandId.LookupPostableCommandId(PostableCommand.CurtainGrid));
        commandIds.Add("ID_OBJECTS_MULLION", RevitCommandId.LookupPostableCommandId(PostableCommand.CurtainWallMullion));
        commandIds.Add("ID_OBJECTS_RAILING", RevitCommandId.LookupPostableCommandId(PostableCommand.Railing));
        commandIds.Add("ID_OBJECTS_RAILING_ON_HOST", RevitCommandId.LookupPostableCommandId(PostableCommand.PlaceOnStairOrRamp));
        commandIds.Add("ID_OBJECTS_RAMP", RevitCommandId.LookupPostableCommandId(PostableCommand.Ramp));
        commandIds.Add("ID_OBJECTS_STAIRS", RevitCommandId.LookupPostableCommandId(PostableCommand.Stair));
        commandIds.Add("ID_OBJECTS_STAIRS_LEGACY", RevitCommandId.LookupPostableCommandId(PostableCommand.StairPath));
        commandIds.Add("ID_OBJECTS_MODELTEXT", RevitCommandId.LookupPostableCommandId(PostableCommand.ModelText));
        commandIds.Add("ID_OBJECTS_PROJECT_CURVE", RevitCommandId.LookupPostableCommandId(PostableCommand.ModelLine));
        commandIds.Add("ID_OBJECTS_PLACE_GROUP", RevitCommandId.LookupPostableCommandId(PostableCommand.PlaceDetailGroup));
        commandIds.Add("ID_EDIT_GROUP", RevitCommandId.LookupPostableCommandId(PostableCommand.CreateGroup));
        commandIds.Add("ID_LOAD_INTO_PROJECTS", RevitCommandId.LookupPostableCommandId(PostableCommand.LoadAsGroup));
        commandIds.Add("ID_OBJECTS_ROOM", RevitCommandId.LookupPostableCommandId(PostableCommand.Room));
        commandIds.Add("ID_OBJECTS_AREA_SEPARATION", RevitCommandId.LookupPostableCommandId(PostableCommand.RoomSeparator));
        commandIds.Add("ID_OBJECTS_ROOM_TAG", RevitCommandId.LookupPostableCommandId(PostableCommand.RoomTag));
        commandIds.Add("ID_OBJECTS_AREA_TAG", RevitCommandId.LookupPostableCommandId(PostableCommand.AreaTag));
        commandIds.Add("ID_BUTTON_TAG_ALL", RevitCommandId.LookupPostableCommandId(PostableCommand.TagAllNotTagged));
        commandIds.Add("ID_VIEW_NEW_AREASCHEME", RevitCommandId.LookupPostableCommandId(PostableCommand.AreaPlan));
        commandIds.Add("ID_OBJECTS_AREA", RevitCommandId.LookupPostableCommandId(PostableCommand.Area));
        commandIds.Add("ID_OBJECTS_AREASCHEME_BOUNDARY", RevitCommandId.LookupPostableCommandId(PostableCommand.AreaBoundary));
        commandIds.Add("ID_SETTINGS_COLORFILLSCHEMES", RevitCommandId.LookupPostableCommandId(PostableCommand.ColorSchemes));
        commandIds.Add("ID_SETTING_AREACALCULATIONS", RevitCommandId.LookupPostableCommandId(PostableCommand.AreaAndVolumeComputations));
        commandIds.Add("ID_CREATE_OPENING_BY_FACE_TB", RevitCommandId.LookupPostableCommandId(PostableCommand.OpeningByFace));
        commandIds.Add("ID_CREATE_SHAFT_OPENING_TB", RevitCommandId.LookupPostableCommandId(PostableCommand.ShaftOpening));
        commandIds.Add("ID_CREATE_WALL_OPENING_TB", RevitCommandId.LookupPostableCommandId(PostableCommand.WallOpening));
        commandIds.Add("ID_CREATE_VERTICAL_OPENING_TB", RevitCommandId.LookupPostableCommandId(PostableCommand.VerticalOpening));
        commandIds.Add("ID_CREATE_DORMER_OPENING_TB", RevitCommandId.LookupPostableCommandId(PostableCommand.DormerOpening));
        commandIds.Add("ID_OBJECTS_LEVEL", RevitCommandId.LookupPostableCommandId(PostableCommand.Level));
        commandIds.Add("ID_OBJECTS_GRID", RevitCommandId.LookupPostableCommandId(PostableCommand.Grid));
        commandIds.Add("ID_OBJECTS_REFERENCE_CURVE", RevitCommandId.LookupPostableCommandId(PostableCommand.ReferenceLine));
        commandIds.Add("ID_OBJECTS_CLINE", RevitCommandId.LookupPostableCommandId(PostableCommand.ReferencePlane));
        commandIds.Add("ID_SKETCH_PLANE_TOOL", RevitCommandId.LookupPostableCommandId(PostableCommand.SetWorkPlane));
        commandIds.Add("ID_PICK_WORKPLANE", RevitCommandId.LookupPostableCommandId(PostableCommand.PickAPlane));
        commandIds.Add("ID_SKETCH_GRID_VIS", RevitCommandId.LookupPostableCommandId(PostableCommand.ShowWorkPlane));
        commandIds.Add("ID_WORKPLANE_VIEW", RevitCommandId.LookupPostableCommandId(PostableCommand.FormWorkPlaneView));
        
        //Structure
        commandIds.Add("ID_OBJECTS_BEAM", RevitCommandId.LookupPostableCommandId(PostableCommand.Beam));
        commandIds.Add("ID_OBJECTS_TRUSS", RevitCommandId.LookupPostableCommandId(PostableCommand.StructuralTrusses));
        commandIds.Add("ID_OBJECTS_BRACE", RevitCommandId.LookupPostableCommandId(PostableCommand.Brace));
        commandIds.Add("ID_OBJECTS_JOIST_SYSTEM", RevitCommandId.LookupPostableCommandId(PostableCommand.AutomaticBeamSystem));
        commandIds.Add("ID_STRUCTURAL_CONNECTION_DIRECT_CREATION", RevitCommandId.LookupPostableCommandId(PostableCommand.StructuralConnection));
        commandIds.Add("ID_STRUCTURAL_AUTO_CONNECTION", RevitCommandId.LookupPostableCommandId(PostableCommand.AutomaticBeamSystem));
        commandIds.Add("ID_STEEL_PLAYLIST_DYNAMO", RevitCommandId.LookupPostableCommandId(PostableCommand.DynamoPlayerForSteel));
        commandIds.Add("ID_OBJECTS_ISOLATED_FOOTING", RevitCommandId.LookupPostableCommandId(PostableCommand.Isolated));
        commandIds.Add("ID_OBJECTS_CONTINUOUS_FOOTING", RevitCommandId.LookupPostableCommandId(PostableCommand.Wall));
        commandIds.Add("ID_OBJECTS_FOOTING_SLAB", RevitCommandId.LookupPostableCommandId(PostableCommand.Slab));
        commandIds.Add("ID_REBAR_PLACE", RevitCommandId.LookupPostableCommandId(PostableCommand.SlabEdgeFloor));
        commandIds.Add("ID_REBAR_SYSTEM_SKETCH", RevitCommandId.LookupPostableCommandId(PostableCommand.Area));
        commandIds.Add("ID_PATH_REIN_SKETCH", RevitCommandId.LookupPostableCommandId(PostableCommand.StructuralPathReinforcement));
        commandIds.Add("ID_FABRIC_DISTR_SYSTEM_SKETCH", RevitCommandId.LookupPostableCommandId(PostableCommand.StructuralFabricArea));
        commandIds.Add("ID_FABRIC_SINGLE_PLACEMENT", RevitCommandId.LookupPostableCommandId(PostableCommand.SingleFabricSheetPlacement));
        commandIds.Add("ID_CONCRETE_COVER", RevitCommandId.LookupPostableCommandId(PostableCommand.EditRebarCover));
        commandIds.Add("ID_REBAR_COUPLER", RevitCommandId.LookupPostableCommandId(PostableCommand.InsertCoupler));
        commandIds.Add("ID_REBAR_COVER_SETTINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.RebarCoverSettings));
        commandIds.Add("ID_REBAR_ABBREVIATION", RevitCommandId.LookupPostableCommandId(PostableCommand.ReinforcementSettings));
        commandIds.Add("ID_NUMBERING_REINF_PARTITIONS", RevitCommandId.LookupPostableCommandId(PostableCommand.ReinforcementNumbers));
        commandIds.Add("ID_STRUCT_CONNECTIVITY_EDIT_MODE_START", RevitCommandId.LookupPostableCommandId(PostableCommand.BeamOrColumnJoins));

        //commandIds.Add("ID_STRUCT_CONNECTIVITY_RESET", RevitCommandId.LookupPostableCommandId(PostableCommand.join));
        //commandIds.Add("ID_CREATE_EXT_ENTITY_PLATE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_EXT_ENTITY_BOLT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_EXT_ENTITY_ANCHOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_EXT_ENTITY_HOLE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_EXT_ENTITY_SHEAR_STUD", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_EXT_ENTITY_WELD", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_EXT_ENTITY_CORNER_CUT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_EXT_ENTITY_BEAM_COPE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_EXT_ENTITY_SHORTENING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_EXT_ENTITY_CONTOUR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STEEL_PARAM_CUT_COPE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STEEL_PARAM_CUT_MITER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STEEL_PARAM_CUT_SAW_CUT_FLANGE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STEEL_PARAM_CUT_SAW_CUT_WEB", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STEEL_PARAM_CUT_THROUGH", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STEEL_PARAM_CUT_BY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_MECHANICAL_DUCT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_DUCT_1LINE_PATH", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_MECHANICAL_FITTING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_MECHANICAL_ACCESSORY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_MECHANICAL_CONVERTTOFLEX", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_MECHANICAL_FLEX", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_MECHANICAL_DIFFUSER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TOGGLE_FABPART_BROWSER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FABRICATION_PART_START_MPR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_FABRICATION_DUCTWORK_STIFFENER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MEP_PNID_MODELER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_MECHANICAL_EQUIPMENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_MECHANICAL_CONTROL_DEVICE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_PIPE_PIPE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PIPE_1LINE_PATH", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PARALLEL_PIPES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_PIPE_FITTING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_PIPE_ACCESSORY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_PIPE_FLEX", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_PLUMBING_EQUIPMENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_PLUMBING_FIXTURE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_SPRINKLER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_WIRE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_WIRE_SPLINE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_WIRE_CHAMFER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_CABLE_TRAY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_CONDUIT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PARALLEL_CONDUIT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_CABLETRAY_FITTING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_CONDUIT_FITTING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_EQUIPMENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_DEVICE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_COMMUNICATION_DEVICE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_DATA_DEVICE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_FIREALARM_DEVICE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_LIGHTING_DEVICE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_NURSECALL_DEVICE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_SECURITY_DEVICE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_TELEPHONE_DEVICE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_LIGHTING_FIXTURE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RVTDOC_LINK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_IFC_LINK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FILE_CADFORMAT_LINK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FILE_TOPOSURFACE_LINK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TOPOGRAPHY_LINK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MARKUPS_LOAD", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RM_CREATE_DECAL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_DECAL_TYPES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_POINT_CLOUD", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COORDINATION_MODEL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COORDINATIONMODEL_ADD_LOCAL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COORDINATIONMODEL_ADD_AUTODESKDOCS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_LINK_PDF", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_LINK_IMAGE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_LINKED_DWG", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FILE_IMPORT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ABS_IMPORT_GBXML", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_IMPORT_FAB_MAJ", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_RASTER_PDF", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_RASTER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_RASTER_SYMBOLS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_IMPORT_FAM_TYPES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FAMILY_LOAD", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FAMILY_LOAD_CLOUD", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_LOAD_GROUP", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_INSERT_VIEWS_FROM_FILE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_INSERT_2D_ELEMENTS_FROM_FILE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ANNOTATIONS_DIMENSION_ALIGNED", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ANNOTATIONS_DIMENSION_LINEAR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ANNOTATIONS_DIMENSION_ANGULAR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ANNOTATIONS_DIMENSION_RADIAL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ANNOTATIONS_DIMENSION_DIAMETER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ANNOTATIONS_DIMENSION_ARCLENGTH", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SPOT_ELEVATION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SPOT_COORDINATE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SPOT_SLOPE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ALIGNMENT_STATION_LABEL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ALIGNMENT_STATION_LABEL_SET", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_DIMENSIONS_LINEAR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_DIMENSIONS_ANGULAR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_DIMENSIONS_RADIAL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_DIMENSIONS_DIAMETER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_SPOT_ELEVATION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_SPOT_COORDINATE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_SPOT_SLOPE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_ALIGNMENT_STATION_LABEL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_DETAIL_CURVES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_FILLED_REGION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MASKING_REGION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_FAMDETAIL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_REPEATING_DETAIL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_LEGEND_COMPONENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_CLOUD", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_PLACE_DETAIL_GROUP", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_INSULATION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_TAG_NOTE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_TEXT_NOTE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CHECK_SPELLING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FIND_REPLACE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_BUTTON_TAG", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_BEAM_ANNOTATION_PLACEMENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TAG_MULTI", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TAG_MATERIAL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_MEP_SPACE_TAG", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_NEW_REFERENCE_VIEWER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STAIRS_TRISER_NUMBER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MULTI_REFERENCE_ANNOTATION_ALIGNED", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MULTI_REFERENCE_ANNOTATION_LINEAR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_KEYNOTE_ELEMENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_KEYNOTE_MATERIAL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_KEYNOTE_USER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_KEYNOTING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_TAGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_MECHANICAL_COLOR_FILL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_PIPING_COLOR_FILL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_ROOM_FILL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_FAM_ANN_INST", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_SPAN_DIR_SYM", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_BEAM_SYSTEM_TAG", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_STAIRS_PATH", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_REBAR_SYSTEM_SPAN_SYM", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_PATH_REIN_SPAN_SYM", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PLACE_BENDING_DETAIL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FABRIC_SYSTEM_PLACE_SPANSYMBOL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ANALYTICAL_MODEL_MEMBERS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_ANALYTICAL_MODEL_PANEL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_ANALYTICAL_MODEL_PANEL_BY_EXTRUSION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_ANALYTICAL_LINK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECT_BC", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ANALYTICAL_MODEL_LOADS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ANALYTICAL_AUTOMATION_PLAYLIST_DYNAMO", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STRUCTURAL_SETTINGS_LOAD_CASES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STRUCTURAL_SETTINGS_LOAD_COMB", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STRUCTURAL_SETTINGS_BOUND_COND", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STRUCTURAL_SETTINGS_LOADS_SCALING_DISPLAY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_AM_EDIT_MODE_START", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RESET_ANALYTICAL_MODEL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COMMAND_CHECK_MEMBER_SUPPORTS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COMMAND_ANALYTICAL_CONSISTENCY_CHECKS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_MEP_SPACE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_MEP_SPACE_SEPARATION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MEP_SPACE_NAMING_UTILITY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_HVAC_ZONE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_HVAC_LOADS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_VIEW_PANEL_SCHEDULE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_SCHEDULE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MEP_DUCT_PRESSURE_LOSS_REPORT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MEP_PIPE_PRESSURE_LOSS_REPORT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_CHECK_DUCT_SYSTEMS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_CHECK_PIPE_SYSTEMS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_CHECK_CIRCUITS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SHOWDISCONNECTS_BUTTON", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_GEO_MANAGE_LOCATIONS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MEP_CREATE_SYSTEM_ZONE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ENABLE_ENERGY_ANALYSIS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_DISABLE_ENERGY_ANALYSIS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ENERGY_MODEL_UPDATE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RUN_SYSTEMS_ANALYSIS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CEA_LAUNCH_ANALYSIS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CEA_OPTIMIZE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SYSTEMS_ANALYSIS_INSIGHT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SYSTEMS_ANALYSIS_RESULTS_INSIGHT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CEA_VIEW_ENERGY_DATA", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ANALYTICAL_AREA_BASED_LOAD_BOUNDARY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_SHOW_ABL_SEPARATION_LINE_OPEN_END", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_HIDE_ABL_SEPARATION_LINE_OPEN_END", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("IDS_RBS_ANALYTICAL_LOADZONE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_ANALYSIS_ADD_EQUIPMENT_LOAD", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PATH_OF_TRAVEL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PATH_OF_TRAVEL_SHOW_OBSTACLES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MULTIPLE_PATHS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ONE_WAY_INDICATOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PEOPLE_CONTENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SPATIAL_GRID", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SHOW_MASS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_INPLACE_MASS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_MASS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_LAUNCH_FORMIT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SITE_TOPO_SURFACE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SITE_TOPO_SOLID", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SITE_TOPO_SOLID_FROM_IMPORT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SITE_COMPONENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SITE_PARKING_COMPONENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SITE_PROPERTYLINE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SITE_LABEL_CONTOURS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SITE_BUILDINGPAD", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PROPERTY_LINE_DATA", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SITE_GRADE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SPLIT_SURFACE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MERGE_SURFACE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SITE_AREA", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TEAM", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_WORKSET_EDITING_REQUESTS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COLLABORATE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COLLABORATE_360", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_PARTITIONS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_GRAY_INACTIVE_WORKSET_GRAPHICS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FILE_SAVE_TO_CENTRAL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FILE_SAVE_TO_CENTRAL_SHORTCUT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_WORKSETS_RELOAD_LATEST", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RELINQUISH_ALL_MINE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_WORKSHARING_MONITOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("RibbonButton_ManageConnectionToARevitServerAccelerator", PostableComman.None));
        //commandIds.Add("ID_PARTITIONS_SHOW_HISTORY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FILE_BACKUPS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COLLABORATE_BROWSER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEWS_FOR_A360", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_REPAIR_CENTRAL_MODEL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COPY_WATCH_CURRENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COPY_WATCH_LINK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RECONCILE_CURRENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RECONCILE_LINK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COPY_SETTINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TOGGLE_HOST_BY_LINK_BROWSER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_INTERFERENCE_CHECK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_INTERFERENCE_REPORT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SHARED_VIEWS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CLOUD_DATA_EXCHANGE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_APPLY_VIEW_TEMPLATE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_VIEW_TEMPLATE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_VIEWTEMPLATES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_CATEGORY_VISIBILITY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_FILTERS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_THIN_LINES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_HIDE_ELEMENTS_EDITOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_UNHIDE_ELEMENTS_EDITOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_CUT_BOUNDARY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PHOTO_RENDERING_VIEW", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PHOTO_RENDER_IN_CLOUD", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PHOTO_RENDER_GALLERY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OPEN_IN_TWINMOTION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TWINMOTION_DIRECT_LINK_AUTOSYNC_ENABLE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TWINMOTION_DIRECT_LINK_AUTOSYNC_DISABLE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TWINMOTION_DIRECT_LINK_SYNCHRONIZE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TWINMOTION_DIRECT_LINK_CONNECTIONS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TWINMOTION_EXPORT_TO_DATASMITH_FILE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TWINMOTION_MESSAGES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TWINMOTION_SETTINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_DEFAULT_3DVIEW", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_PERSP_VIEW", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_3DVIEW", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_WALKTHROUGH", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_SECTION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_CALLOUT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_CALLOUT_SKETCH", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_PLAN", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_STRUCTURAL_PLAN", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_NEW_PLAN_REGION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_RCP", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_BUTTON_BRACING_ELEVATION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_BUTTON_INTERIOR_ROOM_ELEVATION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_DRAFTING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PRJBROWSER_COPY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_DUPLICATE_WITH_DETAILING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_DEPENDENT_VIEW", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_LEGEND", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_KEYNOTE_LEGEND", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_GRAPH_SCHED_COLUMN", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_MATERIAL_TAKEOFF", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_DRAWING_LIST", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_NOTE_BLOCK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_NEW_VIEWLIST", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_REVISION_SCHEDULE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VOLUME_OF_INTEREST", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_NEW_SHEET", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_PLACE_VIEW", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_PLACE_TITLEBLOCK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_REVISIONS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_GUIDE_GRID", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_NEW_MATCHLINE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEWPORT_ACTIVATE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEWPORT_ACTIVATE_BASE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("manage_views", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_CLOSE_INACTIVE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_TAB", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_WINDOW_TILE_VERT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("HID_APPLICATION_ELEMENTS_RibbonListButton", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CANVAS_THEME_SWITCH", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_MATERIALS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_OBJECTSTYLES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_SNAPPING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_PROJECT_INFORMATION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_FORGE_PARAMETERS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_PROJECT_PARAMETERS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FILE_EXTERNAL_PARAMETERS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_GLOBAL_PARAMETERS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TRANSFER_PROJECT_STANDARDS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PURGE_UNUSED", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_UNITS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STRUCTURAL_SETTINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STRUCTURAL_CONNECTION_SETTINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_MECHANICAL_SETTINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_SETTINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MEP_FABRICATION_SETTINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_LOAD_CLASSIFICATION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ELECTRICAL_DEMAND_FACTOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_BUILDINGSPACE_TYPE_SETTINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MEP_ELECTRICAL_ANALYSIS_SETTINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MEP_PNID_SETTINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_PANEL_SCHEDULE_MANAGE_TEMPLATES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_PANEL_SCHEDULE_EDIT_A_TEMPLATE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_GEO_ACQUIRE_COORDINATES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_GEO_PUBLISH_COORDINATES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RESET_SHARED_COORDINATES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SPECIFY_SHARED_COORDINATES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_REPORT_SHARED_COORDINATES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_REPORT_COORDINATES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RELOCATE_SHARED_COORDINATES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RELOCATE_PROJECT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ROTATE_SHARED_COORDINATES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ROTATE_TRUE_NORTH", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MIRROR_PROJECT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ROTATE_PROJECT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_DESIGNOPTIONS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_ADDTODESIGNOPTIONSET", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_PICKS_OPTION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_GENERATIVE_DESIGN_CREATE_STUDY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_GENERATIVE_DESIGN_EXPLORE_OUTCOMES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_STARTING_VIEW", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SETTINGS_PHASES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FILTERS_SELECTION_SAVE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RETRIEVE_FILTERS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_SELECTIONS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_IDS_OF_SELECTION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SELECT_BY_ID", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_REVIEW_WARNINGS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TOOLS_MACROS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TOOLS_MACROSECURITY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VISUAL_PROGRAMMING_DYNAMO", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_PLAYLIST_DYNAMO", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_TYPE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TOGGLE_PROPERTIES_PALETTE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_FAMILYHOST", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_FAMILY_TYPE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_REBAR_CURVE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MAJOR_SEGMENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_CURVE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TRUSS_TOP_CHORD_CURVE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TRUSS_WEB_CURVE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TRUSS_BOTTOM_CHORD_CURVE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SPLIT_FACE_IN_NEW_FAMILIES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_EXTRUSION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_BLEND", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_REVOLUTION", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_SWEEP", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_SWEPTBLEND", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_EXTRUSION_CUT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_BLEND_CUT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_REVOLUTION_CUT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_SWEEP_CUT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_SWEPTBLEND_CUT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_OPENING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_CONTROL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ADD_ELECTRICAL_CONNECTOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ADD_DUCT_CONNECTOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ADD_PIPE_CONNECTOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ADD_CABLETRAY_CONNECTOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_RBS_ADD_CONDUIT_CONNECTOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_REBAR_SHAPE_ALLOWABLE_BAR_TYPES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OBJECTS_VIEW_DIR_SPEC_CURVE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_PASTE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_PASTE_ALIGNED_LEVEL_BY_NAME", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_PASTE_ALIGNED_VIEWS_BY_NAME", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_PASTE_ALIGNED", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_PASTE_ALIGNED_SAME_PLACE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_PASTE_ALIGNED_PICK_LEVEL", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_CUT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_COPY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_MATCH_TYPE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_PAINT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_UNPAINT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COPING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_UNCOPING", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CUT_HOST", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_UNCUT_HOST", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_JOIN_ELEMENTS_EDITOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_UNJOIN_ELEMENTS_EDITOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SWITCH_JOIN_ORDER_EDITOR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_JOIN_ROOF", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_BEAM_JOINS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_WALL_JOINS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SPLIT_FACE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_DEMOLISH", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TOGGLE_ACTIVATE_CONTROLS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_ALIGN", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_MOVE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_OFFSET", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_MOVE_COPY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_MIRROR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_ROTATE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_MIRROR_LINE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TRIM_EXTEND_CORNER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SPLIT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_CREATE_PATTERN", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_REPEAT_COMPONENT", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TRIM_EXTEND_SINGLE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SPLIT_WITH_GAP", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_SCALE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TRIM_EXTEND_MULTIPLE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_UNLOCK_ELEMENTS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_LOCK_ELEMENTS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_BUTTON_DELETE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_HIDE_ELEMENTS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_HIDE_CATEGORY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_GO_FILTER", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_DISPLACEMENT_CREATE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_OVERRIDE_ELEMENTS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_OVERRIDE_CATEGORY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_LINEWORK", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_VIEW_APPLY_SELECTION_BOX", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MEASURE_LINE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_MEASURE_PICK_LINES", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_ASSEMBLY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_CREATE_PARTS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_EDIT_CREATE_SIMILAR", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_END_INPLACE_FAMILY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_QUIT_INPLACE_FAMILY", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_END_INPLACE_MASS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_QUIT_INPLACE_MASS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_END_INPLACE_ZONE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_QUIT_INPLACE_ZONE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_LOAD_INTO_PROJECTS_CLOSE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_COUPLER_STATUS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_TURN_ON_MULTI_PLANAR_SHAPE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_SHAPE_STATUS", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_LOAD_INTO_PROJECTS_REBAR_SHAPE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));
        //commandIds.Add("ID_LOAD_INTO_PROJECTS_CLOSE_REBAR_SHAPE", RevitCommandId.LookupPostableCommandId(PostableCommand.None));




    }
}
